`timescale 1ns / 1ps

// Read-only multi-frame source image store, one byte (8-bit grayscale) per
// pixel, raster order, NUM_FRAMES frames concatenated back-to-back into a
// single flat array, initialized from a $readmemh .mem file generated by
// tools/gen_test_image.py, tools/img_to_mem.py, or tools/video_to_mem.py.
//
// Streams continuously in raster order at one pixel per cycle whenever
// rd_en is high, wrapping back to pixel 0 of the current frame at the end
// of that frame. Pulse frame_start to reset the read position to (0,0) on
// demand -- this also latches frame_idx into the frame base address, so a
// frame_idx change mid-stream never corrupts an in-flight render; the new
// frame only takes effect starting from the next frame_start.
module frame_store #(
    parameter  int    IMG_WIDTH   = 96,
    parameter  int    IMG_HEIGHT  = 64,
    parameter  int    PIX_W       = 8,
    parameter  int    NUM_FRAMES  = 24,
    parameter  string INIT_FILE   = "frame_store.mem",
    localparam int    COL_W        = $clog2(IMG_WIDTH),
    localparam int    ROW_W        = $clog2(IMG_HEIGHT),
    localparam int    NUM_PIX      = IMG_WIDTH * IMG_HEIGHT,
    localparam int    LOCAL_ADDR_W = $clog2(NUM_PIX),
    localparam int    ADDR_W       = $clog2(NUM_PIX * NUM_FRAMES),
    localparam int    FRAME_IDX_W  = (NUM_FRAMES > 1) ? $clog2(NUM_FRAMES) : 1
) (
    input logic clk,
    input logic rst,

    input logic frame_start,
    input logic rd_en,
    input logic [FRAME_IDX_W-1:0] frame_idx,

    output logic              pix_valid,
    output logic [ PIX_W-1:0] pix_data,
    output logic [  COL_W-1:0] col,
    output logic [  ROW_W-1:0] row
);

  (* rom_style = "block" *) logic [PIX_W-1:0] mem[0:NUM_PIX*NUM_FRAMES-1];
  initial $readmemh(INIT_FILE, mem);

  logic [LOCAL_ADDR_W-1:0] local_addr;
  logic [      ADDR_W-1:0] frame_base;
  logic [       COL_W-1:0] col_r;
  logic [       ROW_W-1:0] row_r;
  logic                    valid_r;

  always_ff @(posedge clk) begin
    if (rst || frame_start) begin
      local_addr <= '0;
      col_r      <= '0;
      row_r      <= '0;
      valid_r    <= 1'b0;
      frame_base <= ADDR_W'(frame_idx) * ADDR_W'(NUM_PIX);
    end else if (rd_en) begin
      valid_r    <= 1'b1;
      local_addr <= (local_addr == LOCAL_ADDR_W'(NUM_PIX - 1)) ? '0 : local_addr + 1'b1;
      if (col_r == COL_W'(IMG_WIDTH - 1)) begin
        col_r <= '0;
        row_r <= (row_r == ROW_W'(IMG_HEIGHT - 1)) ? '0 : row_r + 1'b1;
      end else begin
        col_r <= col_r + 1'b1;
      end
    end else begin
      valid_r <= 1'b0;
    end
  end

  assign pix_data  = mem[frame_base+ADDR_W'(local_addr)];
  assign pix_valid = valid_r;
  assign col       = col_r;
  assign row       = row_r;

endmodule
