`timescale 1ns / 1ps

// Read-only source image, one byte (8-bit grayscale) per pixel, raster
// order, initialized from a $readmemh .mem file generated by
// tools/gen_test_image.py or tools/img_to_mem.py.
//
// Streams continuously in raster order at one pixel per cycle whenever
// rd_en is high, wrapping back to pixel 0 at the end of the frame.
// Pulse frame_start to reset the read position to (0,0) on demand (used
// when the top level wants to kick off a fresh render pass after the mode
// switches change).
module image_rom #(
    parameter  int    IMG_WIDTH  = 96,
    parameter  int    IMG_HEIGHT = 64,
    parameter  int    PIX_W      = 8,
    parameter  string INIT_FILE  = "test_image.mem",
    localparam int    COL_W      = $clog2(IMG_WIDTH),
    localparam int    ROW_W      = $clog2(IMG_HEIGHT),
    localparam int    NUM_PIX    = IMG_WIDTH * IMG_HEIGHT,
    localparam int    ADDR_W     = $clog2(NUM_PIX)
) (
    input logic clk,
    input logic rst,

    input logic frame_start,
    input logic rd_en,

    output logic             pix_valid,
    output logic [PIX_W-1:0] pix_data,
    output logic [ COL_W-1:0] col,
    output logic [ ROW_W-1:0] row
);

  (* rom_style = "block" *) logic [PIX_W-1:0] mem[0:NUM_PIX-1];
  initial $readmemh(INIT_FILE, mem);

  logic [ADDR_W-1:0] addr;
  logic [ COL_W-1:0] col_r;
  logic [ ROW_W-1:0] row_r;
  logic              valid_r;

  always_ff @(posedge clk) begin
    if (rst || frame_start) begin
      addr    <= '0;
      col_r   <= '0;
      row_r   <= '0;
      valid_r <= 1'b0;
    end else if (rd_en) begin
      valid_r <= 1'b1;
      addr    <= (addr == ADDR_W'(NUM_PIX - 1)) ? '0 : addr + 1'b1;
      if (col_r == COL_W'(IMG_WIDTH - 1)) begin
        col_r <= '0;
        row_r <= (row_r == ROW_W'(IMG_HEIGHT - 1)) ? '0 : row_r + 1'b1;
      end else begin
        col_r <= col_r + 1'b1;
      end
    end else begin
      valid_r <= 1'b0;
    end
  end

  assign pix_data  = mem[addr];
  assign pix_valid = valid_r;
  assign col        = col_r;
  assign row        = row_r;

endmodule
